#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: _MissionGen_PARENT

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass _MissionGen_PARENT._MissionGen_PARENT_C
// 0x0000 (0x06A8 - 0x06A8)
class U_MissionGen_PARENT_C : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"_MissionGen_PARENT_C">();
	}
	static class U_MissionGen_PARENT_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<U_MissionGen_PARENT_C>();
	}
};
static_assert(alignof(U_MissionGen_PARENT_C) == 0x000008, "Wrong alignment on U_MissionGen_PARENT_C");
static_assert(sizeof(U_MissionGen_PARENT_C) == 0x0006A8, "Wrong size on U_MissionGen_PARENT_C");

}

