#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UACCommon

#include "Basic.hpp"

#include "UACCommon_classes.hpp"
#include "UACCommon_parameters.hpp"


namespace SDK
{

// Function UACCommon.UACNetComponent.SendClientHello
// (Net, NetReliable, Native, Event, Public, NetClient)

void UUACNetComponent::SendClientHello()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UACNetComponent", "SendClientHello");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UACCommon.UACNetComponent.SendPacketToClient
// (Net, NetReliable, Native, Event, Public, NetClient)
// Parameters:
// EUACPacketType                          Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<uint8>                           Packet                                                 (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UUACNetComponent::SendPacketToClient(EUACPacketType Type, const TArray<uint8>& Packet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UACNetComponent", "SendPacketToClient");

	Params::UACNetComponent_SendPacketToClient Parms{};

	Parms.Type = Type;
	Parms.Packet = std::move(Packet);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UACCommon.UACNetComponent.SendPacketToServer
// (Net, NetReliable, Native, Event, Public, NetServer, NetValidate)
// Parameters:
// EUACPacketType                          Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// TArray<uint8>                           Packet                                                 (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UUACNetComponent::SendPacketToServer(EUACPacketType Type, const TArray<uint8>& Packet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UACNetComponent", "SendPacketToServer");

	Params::UACNetComponent_SendPacketToServer Parms{};

	Parms.Type = Type;
	Parms.Packet = std::move(Packet);

	UObject::ProcessEvent(Func, &Parms);
}

}

